robot_type: inspire
embodiment_type: bimanual
task: stir_beaker
seed: 4
dataset_dir: example_datasets
dataset_name: oakink
data_id: 4
model_path: /home/ubuntu/spider/example_datasets/processed/oakink/inspire/bimanual/stir_beaker/4/../scene.xml
data_path: /home/ubuntu/spider/example_datasets/processed/oakink/inspire/bimanual/stir_beaker/4/trajectory_kinematic.npz
simulator: mjwp
device: cuda:0
sim_dt: 0.01
ctrl_dt: 0.4
ref_dt: 0.02
render_dt: 0.02
horizon: 2.0
knot_dt: 0.4
max_sim_steps: 1154
nconmax_per_env: 100
njmax_per_env: 350
num_dyn: 1
num_dr: 1
pair_margin_range:
- -0.005
- 0.005
xy_offset_range:
- -0.005
- 0.005
perturb_force: 0.0
perturb_torque: 0.0
num_samples: 1024
temperature: 1.0
max_num_iterations: 32
improvement_threshold: 0.01
improvement_check_steps: 2
terminate_resample: false
object_pos_threshold: 0.1
object_rot_threshold: 0.3
base_pos_threshold: 0.5
base_rot_threshold: 0.4
use_torch_compile: true
first_ctrl_noise_scale: 0.5
last_ctrl_noise_scale: 1.0
final_noise_scale: 0.1
exploit_ratio: 0.01
exploit_noise_scale: 0.01
joint_noise_scale: 0.03
pos_noise_scale: 0.01
rot_noise_scale: 0.01
base_pos_rew_scale: 0.1
base_rot_rew_scale: 0.03
joint_rew_scale: 0.003
pos_rew_scale: 1.0
rot_rew_scale: 0.3
vel_rew_scale: 0.0001
terminal_rew_scale: 1.0
contact_rew_scale: 0.0
show_viewer: true
viewer: ''
rerun_spawn: true
save_video: true
save_info: true
save_rerun: false
save_metrics: true
save_config: true
trace_dt: 0.02
num_trace_uniform_samples: 4
num_trace_topk_samples: 2
trace_site_ids:
- 33
- 50
- 3
- 6
- 9
- 12
- 15
- 19
- 22
- 25
- 28
- 31
horizon_steps: 200
knot_steps: 40
ref_steps: 2
ctrl_steps: 40
nq_obj: 14
nq: 50
nv: 48
nu: 36
npair: 621
beta_traj: 0.930572040929699
output_dir: /home/ubuntu/spider/example_datasets/processed/oakink/inspire/bimanual/stir_beaker/4
