#!/bin/bash
#SBATCH --job-name=spider            # Name of job
#SBATCH --partition=gpu              # Partition to submit to
#SBATCH --nodes=1                    # Number of nodes
#SBATCH --exclude=dgx2-compute-01,jjs533-compute-03,elor-compute-02,taylor-compute-01,snavely-compute-04,snavely-compute-05,snavely-compute-06,snavely-compute-07,snavely-compute-09,snavely-compute-10,snavely-compute-11,snavely-compute-12,bhattacharjee-compute-02,seo-compute-02
#SBATCH --cpus-per-task=16           # Number of CPU cores per task
#SBATCH --ntasks=1                   # Number of tasks
#SBATCH --gres=gpu:1                 # Number of GPUs
#SBATCH --mem=32G                    # Memory allocation
#SBATCH --time=48:00:00              # Time limit
#SBATCH --output=slurm_out/slurm-%j.out        # Standard output log file
echo $HOSTNAME
nvidia-smi
python examples/run_mjwp.py --mink
