#!/bin/bash

#SBATCH --job-name=spider               # Name of job
#SBATCH --partition=gpu
#SBATCH --nodes=1                    # Number of nodes
#SBATCH --cpus-per-task=16           # Number of CPU cores per task
#SBATCH --ntasks=1                   # Number of tasks
#SBATCH --gres=gpu:1                 # Number of GPUs
#SBATCH --mem=32G                   # Memory allocation
#SBATCH --time=48:00:00              # Time limit
#SBATCH --output=slurm_out/slurm-%j.out        # Standard output log file
#SBATCH --exclude=bhattacharjee-compute-02

$ECHO hostname
nvidia-smi
python examples/run_mjwp.py \
    num_samples=4096 \
